In [1]:
import pandas as pd
import re

# Open and read the file
with open('WhatsApp Chat with Akshat jain TMU.txt', 'r', encoding='utf-8') as f:
    data = f.read()

# Remove "AM" and "PM" (including with space variations like non-breaking spaces)
#data_cleaned = re.sub(r'\s?[APap][Mm]', '', data)

# Print or write the cleaned data
#print(data_cleaned)

# Optional: save to a new file
#with open('Cleaned_Chat.txt', 'w', encoding='utf-8') as f:
    #f.write(data_cleaned)

In [2]:
print(data)

9/7/23, 9:21 AM - Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. Learn more.
10/10/23, 12:32 PM - Akshat Jain TMU is a contact
10/10/23, 12:32 PM - Akshat Jain TMU: Hi
10/10/23, 12:32 PM - Akshat Jain TMU: <Media omitted>
10/31/23, 9:06 PM - Akshat Jain TMU: Bhai mam ne jo kal likhaya tha bo semd kro do
10/31/23, 9:07 PM - Akshat Jain TMU: Chemistry
10/31/23, 10:02 PM - Arpit Jain: <Media omitted>
10/31/23, 10:03 PM - Arpit Jain: <Media omitted>
10/31/23, 10:43 PM - Arpit Jain: Done
10/31/23, 10:47 PM - Akshat Jain TMU: Hao
10/31/23, 10:47 PM - Akshat Jain TMU: Thanks
10/31/23, 11:29 PM - Arpit Jain: 👍
11/3/23, 11:19 PM - Akshat Jain TMU: Iske aage ka send kro
11/3/23, 11:19 PM - Akshat Jain TMU: Flash and fire tk
11/9/23, 3:37 PM - Arpit Jain: Hlo
11/9/23, 3:38 PM - Arpit Jain: You deleted this message
11/9/23, 3:38 PM - Arpit Jain: Kal aur parso jo kaam hua hai class me vo send kar do
11/9/23, 3:43 PM - Akshat Jain TMU: Bhai me khud collage nhi gaya
11/9/23, 3:43 PM - Akshat Jain TMU: Gahr pe hu
11/9/23, 3:44 PM - Arpit Jain: Are tum 8 ko gaye the
11/9/23, 3:45 PM - Arpit Jain: 7 aur 6 ke bhej do
11/9/23, 3:45 PM - Arpit Jain: Yaar
11/9/23, 4:16 PM - Akshat Jain TMU: Ha
11/9/23, 6:24 PM - Arpit Jain: You deleted this message
11/9/23, 6:30 PM - Arpit Jain: To send kar do
11/9/23, 8:53 PM - Akshat Jain TMU: <Media omitted>
11/9/23, 8:53 PM - Akshat Jain TMU: <Media omitted>
11/9/23, 8:53 PM - Akshat Jain TMU: <Media omitted>
11/9/23, 8:53 PM - Akshat Jain TMU: <Media omitted>
11/24/23, 8:36 PM - Arpit Jain: Ok
11/24/23, 8:45 PM - Akshat Jain TMU: Kya ok
2/13/24, 4:11 PM - Akshat Jain TMU: Print kya karwana English me
2/13/24, 4:11 PM - Akshat Jain TMU: Batao
2/13/24, 4:15 PM - Arpit Jain: Jo mam ne pdf bheji hai group me English communication bale vo print karani hai
2/13/24, 4:15 PM - Arpit Jain: Ok
2/13/24, 4:15 PM - Akshat Jain TMU: Sari
2/13/24, 4:15 PM - Akshat Jain TMU: Karani
2/13/24, 4:15 PM - Arpit Jain: Ha sari
2/13/24, 4:15 PM - Akshat Jain TMU: Ok
2/13/24, 4:15 PM - Arpit Jain: Ok
2/13/24, 4:15 PM - Akshat Jain TMU: Or sequence
2/13/24, 4:15 PM - Akshat Jain TMU: Kesa kya rkhna
2/13/24, 4:16 PM - Arpit Jain: Syllabus ke hisab se
2/13/24, 4:17 PM - Akshat Jain TMU: Tumai total kitne page the
2/13/24, 4:17 PM - Arpit Jain: 65
2/13/24, 4:17 PM - Arpit Jain: Hai
2/13/24, 4:17 PM - Akshat Jain TMU: Tum hame bhejdo
2/13/24, 4:17 PM - Akshat Jain TMU: Konsi karani
2/13/24, 4:18 PM - Arpit Jain: Ok
2/13/24, 4:19 PM - Arpit Jain: Abi bhej rahe ok
2/13/24, 4:19 PM - Akshat Jain TMU: Pdf bhejdo
2/13/24, 4:19 PM - Akshat Jain TMU: Konse karane
2/13/24, 4:19 PM - Arpit Jain: Ok
2/13/24, 4:19 PM - Arpit Jain: <Media omitted>
2/13/24, 4:19 PM - Arpit Jain: <Media omitted>
2/13/24, 4:19 PM - Arpit Jain: <Media omitted>
2/13/24, 4:19 PM - Arpit Jain: <Media omitted>
2/13/24, 4:19 PM - Arpit Jain: <Media omitted>
2/13/24, 4:19 PM - Arpit Jain: <Media omitted>
2/13/24, 4:19 PM - Arpit Jain: <Media omitted>
2/13/24, 4:19 PM - Arpit Jain: <Media omitted>
2/13/24, 4:21 PM - Arpit Jain: Ok
2/22/24, 2:18 PM - Akshat Jain TMU: null
2/22/24, 2:19 PM - Arpit Jain: null
2/22/24, 2:22 PM - Akshat Jain TMU: null
2/22/24, 2:26 PM - Arpit Jain: null
2/22/24, 3:07 PM - Arpit Jain: <Media omitted>
2/22/24, 3:34 PM - Akshat Jain TMU: <Media omitted>
2/22/24, 8:37 PM - Akshat Jain TMU: null
2/22/24, 8:37 PM - Akshat Jain TMU: Tumao
2/22/24, 8:37 PM - Akshat Jain TMU: Phone
2/22/24, 8:37 PM - Akshat Jain TMU: Kai
2/22/24, 8:37 PM - Akshat Jain TMU: Nhi
2/22/24, 8:37 PM - Akshat Jain TMU: Lagt
2/22/24, 8:37 PM - Akshat Jain TMU: ???
2/22/24, 8:37 PM - Akshat Jain TMU: Or mess chal rai ???
2/22/24, 9:03 PM - Arpit Jain: Nahi
2/22/24, 9:03 PM - Arpit Jain: Mai 9 30 PE jauga
2/22/24, 9:03 PM - Arpit Jain: Ok
2/22/24, 9:07 PM - Akshat Jain TMU: Hao
2/22/24, 9:07 PM - Akshat Jain TMU: Ham khaa aye
2/22/24, 10:08 PM - Arpit Jain: Aaj nahi gaye khane
2/22/24, 10:08 PM - Akshat Jain TMU: Ham kha ke agai
2/22/24, 10:19 PM - Arpit Jain: Nahi Aaj nahi khaya sach me
2/22/24, 10:19 PM - Arpit Jain: Ok
2/22/24, 10:20 PM - Arpit Jain: Bhukh lag Rahi aab to
2/22/24, 10:30 PM - Akshat Jain TMU: Ajao
2/22/24, 10:30 PM - Akshat Jain TMU: Nasta kha lo mere room oe
2/22/24, 10:58 PM - Arpit Jain: Are nahi
2/22/24, 10:58 PM - Arpit Jain: Nahi
2/22/24, 11:16 PM - Akshat Jain TMU: Tumao phone kai nhi lagt h
2/22/24, 11:16 PM - Akshat Jain TMU: Incoming seva band ati h
2/23/24, 8:15 AM - Arpit Jain: Are 9753939532 pe lagao lag Jago
2/23/24, 8:15 AM - Arpit Jain: Ok
2/23/24, 8:16 AM - Arpit Jain: Done
2/23/24, 8:52 AM - Akshat Jain TMU: null
2/23/24, 3:16 PM - Akshat Jain TMU: Kal
2/23/24, 3:16 PM - Akshat Jain TMU: Auditorium chalne
2/23/24, 3:16 PM - Akshat Jain TMU: Road safety
2/23/24, 3:16 PM - Akshat Jain TMU: Balao ko
2/23/24, 3:16 PM - Akshat Jain TMU: 2 baje
2/23/24, 4:05 PM - Arpit Jain: Ok
2/24/24, 11:34 AM - Arpit Jain: <Media omitted>
2/26/24, 4:06 PM - Arpit Jain: Hlo
2/26/24, 4:06 PM - Arpit Jain: Hlo
2/26/24, 4:06 PM - Arpit Jain: Are you there
2/26/24, 4:07 PM - Arpit Jain: Hlo
2/26/24, 4:07 PM - Arpit Jain: Response me
2/26/24, 4:07 PM - Arpit Jain: Hlo
2/26/24, 4:07 PM - Arpit Jain: Hlo
2/26/24, 4:44 PM - Akshat Jain TMU: Haaa
2/26/24, 4:44 PM - Akshat Jain TMU: Bolo
2/26/24, 5:24 PM - Akshat Jain TMU: Ka h
2/26/24, 5:24 PM - Akshat Jain TMU: Bolo ab
2/27/24, 2:30 PM - Akshat Jain TMU: <Media omitted>
2/28/24, 8:25 PM - Akshat Jain TMU: Kitne baje tk jo
2/28/24, 8:25 PM - Akshat Jain TMU: ??
2/28/24, 8:27 PM - Arpit Jain: 9
2/28/24, 8:27 PM - Arpit Jain: Baje
2/28/24, 8:28 PM - Akshat Jain TMU: Abhi kya kar rai
2/28/24, 8:29 PM - Akshat Jain TMU: Bhai physics ke notes dedo yr
2/28/24, 8:59 PM - Akshat Jain TMU: Chalo
2/28/24, 8:59 PM - Akshat Jain TMU: Chalo
2/28/24, 8:59 PM - Akshat Jain TMU: Chalo
2/28/24, 8:59 PM - Akshat Jain TMU: Halo
2/28/24, 8:59 PM - Akshat Jain TMU: Chalo
2/28/24, 8:59 PM - Akshat Jain TMU: Chalo
2/28/24, 8:59 PM - Akshat Jain TMU: Chalo
2/28/24, 8:59 PM - Akshat Jain TMU: Halo
2/28/24, 8:59 PM - Akshat Jain TMU: Halo
2/28/24, 8:59 PM - Akshat Jain TMU: Halo
2/28/24, 8:59 PM - Akshat Jain TMU: Halo
2/28/24, 8:59 PM - Akshat Jain TMU: Halo
2/28/24, 11:16 PM - Arpit Jain: Heeeeee
2/28/24, 11:16 PM - Arpit Jain: Haaaaaa
2/28/24, 11:16 PM - Arpit Jain: Hooooo
2/28/24, 11:17 PM - Arpit Jain: Op bolte
2/28/24, 11:17 PM - Arpit Jain: Ok
2/28/24, 11:24 PM - Akshat Jain TMU: Do
2/29/24, 9:58 AM - Akshat Jain TMU: <Media omitted>
2/29/24, 12:41 PM - Akshat Jain TMU: <Media omitted>
3/2/24, 5:47 PM - Akshat Jain TMU: Mandir jaoge ??
3/2/24, 8:56 PM - Arpit Jain: Ha ha
3/2/24, 8:56 PM - Arpit Jain: Ha
3/4/24, 9:50 PM - Akshat Jain TMU: Physics important question
1- Discuss the प्रिंसिपल ऑफ superposition derive the expressuon for the resultant intensity and discuss the condition for maxima and minima (10 marks)
2- obtain the path difference in fresnel biprism and drive the expression for the fringe width and so that fringe width are dark and bright.
3- discuss the method to determine the wavelength of  a monochromatic source using fresnel biprism
4-Derice the expression for path differnece in a thin film of uniform thickness using reflected or transmitted light and  discuss the conditon for maxima
3/4/24, 9:51 PM - Akshat Jain TMU: Method batabe
3/4/24, 9:51 PM - Akshat Jain TMU: Batane
3/4/24, 9:51 PM - Akshat Jain TMU: 3rd bala
3/4/24, 9:52 PM - Akshat Jain TMU: Bolooooooooooooooooooooo
3/4/24, 9:53 PM - Arpit Jain: Are muje nahi pata mene to abhi suna ye
3/4/24, 9:53 PM - Arpit Jain: Are sahi mai
3/4/24, 9:53 PM - Akshat Jain TMU: Bhai pls bata do
3/4/24, 9:53 PM - Akshat Jain TMU: Na tmne math baatai
3/4/24, 9:53 PM - Akshat Jain TMU: Math me bhi chud gai
3/4/24, 9:53 PM - Arpit Jain: Math to hamao bhi long ko galat ho gayo
3/4/24, 9:53 PM - Arpit Jain: Patahe
3/4/24, 9:54 PM - Arpit Jain: Tumne batao
3/4/24, 9:54 PM - Akshat Jain TMU: Ham tumai room pe aa rai
3/4/24, 9:54 PM - Arpit Jain: Kachu math mai
3/4/24, 9:54 PM - Akshat Jain TMU: Hame bata do
3/4/24, 9:54 PM - Akshat Jain TMU: 3rd balo
3/4/24, 9:54 PM - Akshat Jain TMU: Santi se
3/4/24, 9:54 PM - Arpit Jain: Aa jao hum to ja rahe khana khane
3/4/24, 9:54 PM - Arpit Jain: Hiiiiiiiiii
3/4/24, 9:54 PM - Akshat Jain TMU: To kahana kha ke hamai room pe ajaio
3/4/24, 9:54 PM - Arpit Jain: Byyyyyyyyyyyyyyyyyy
3/4/24, 9:54 PM - Akshat Jain TMU: Nooo
3/4/24, 9:54 PM - Akshat Jain TMU: Ruko
3/4/24, 9:54 PM - Arpit Jain: Ok
3/4/24, 9:54 PM - Akshat Jain TMU: Wait
3/4/24, 9:54 PM - Arpit Jain: Ok
3/4/24, 9:54 PM - Arpit Jain: Hahahahahahahha
3/4/24, 9:54 PM - Akshat Jain TMU: Mere room pe aja a
3/4/24, 9:54 PM - Arpit Jain: Ha
3/4/24, 9:55 PM - Akshat Jain TMU: Mujhe bata dena thodi
3/4/24, 9:55 PM - Akshat Jain TMU: 1-2 doubt h
3/4/24, 9:55 PM - Arpit Jain: Aada ghante Mai ok
3/4/24, 9:55 PM - Akshat Jain TMU: Clear kardena bass
3/4/24, 9:55 PM - Akshat Jain TMU: Ok
3/4/24, 9:55 PM - Arpit Jain: Ok
3/4/24, 9:55 PM - Arpit Jain: Byyyyy
3/4/24, 9:55 PM - Akshat Jain TMU: 😚
3/4/24, 9:55 PM - Akshat Jain TMU: Bye
3/4/24, 9:55 PM - Akshat Jain TMU: Sweet heart 💕
4/5/24, 12:18 PM - Arpit Jain: <Media omitted>
4/6/24, 11:31 AM - Akshat Jain TMU: <Media omitted>
4/6/24, 5:20 PM - Akshat Jain TMU: Kai tum hamai drawing bai pencil lai ka
4/6/24, 6:46 PM - Arpit Jain: Nai to
4/6/24, 7:32 PM - Akshat Jain TMU: <Media omitted>
4/6/24, 7:32 PM - Akshat Jain TMU: <Media omitted>
4/6/24, 7:32 PM - Akshat Jain TMU: <Media omitted>
4/6/24, 7:34 PM - Arpit Jain: <Media omitted>
4/6/24, 7:34 PM - Arpit Jain: <Media omitted>
4/6/24, 7:35 PM - Arpit Jain: <Media omitted>
4/6/24, 7:35 PM - Arpit Jain: <Media omitted>
4/6/24, 7:35 PM - Arpit Jain: <Media omitted>
4/8/24, 7:50 PM - Arpit Jain: Hi
4/8/24, 7:50 PM - Akshat Jain TMU: +91 83848 26047
4/8/24, 7:52 PM - Akshat Jain TMU: Bhejdo
4/8/24, 7:52 PM - Arpit Jain: Hao
4/8/24, 7:55 PM - Arpit Jain: Bhej dae
4/8/24, 7:55 PM - Arpit Jain: Ok
4/8/24, 7:56 PM - Akshat Jain TMU: Ha
4/8/24, 7:57 PM - Arpit Jain: Sare nahi ja rahe
4/8/24, 7:57 PM - Akshat Jain TMU: Mene bhej diye
4/8/24, 7:57 PM - Akshat Jain TMU: Rhne do
4/8/24, 7:58 PM - Akshat Jain TMU: Net ka problem ho raha tha
4/8/24, 7:58 PM - Akshat Jain TMU: Ab chalne laga
4/8/24, 7:58 PM - Akshat Jain TMU: Btw thanks
4/8/24, 10:16 PM - Arpit Jain: Ok
4/20/24, 8:12 PM - Akshat Jain TMU: Electrical ki unit 4 me kaha tk padhna h ??
4/22/24, 8:22 AM - Arpit Jain: Pura padna hai
4/29/24, 4:50 PM - Akshat Jain TMU: Newton rings
4/29/24, 7:23 PM - Akshat Jain TMU: <Media omitted>
4/29/24, 7:32 PM - Akshat Jain TMU: Ek introduction ka page hoga or ek thankyou bala
4/29/24, 7:33 PM - Akshat Jain TMU: Apne hisab se ek page choice karlo konsa bologe
Bohi bol dena
Thoda sa hi bolna h jayda nhi
4/29/24, 7:40 PM - Arpit Jain: Pehle dono me se ek karlo
4/29/24, 7:40 PM - Arpit Jain: Vo achhe hai
4/29/24, 7:40 PM - Akshat Jain TMU: Matlb
4/29/24, 7:41 PM - Akshat Jain TMU: Are 5 log bolege
4/29/24, 7:41 PM - Akshat Jain TMU: To ek ek boldo
4/29/24, 7:41 PM - Akshat Jain TMU: Tum
Ham
Arpit cr
4/29/24, 7:41 PM - Akshat Jain TMU: 3 confirm h
4/29/24, 7:41 PM - Arpit Jain: Achhaa
4/29/24, 7:41 PM - Akshat Jain TMU: 2 or chane
4/29/24, 7:41 PM - Akshat Jain TMU: Bo aryan Mishra ki bol raha tha
4/29/24, 7:41 PM - Akshat Jain TMU: Uska abhi confirm nhi h
4/29/24, 7:41 PM - Akshat Jain TMU: Puch ke batunga
4/29/24, 7:43 PM - Arpit Jain: To me dusra bol dunga
4/29/24, 7:43 PM - Arpit Jain: Thike
4/29/24, 7:43 PM - Akshat Jain TMU: Ok
4/29/24, 11:03 PM - Arpit Jain: <Media omitted>
4/29/24, 11:04 PM - Arpit Jain: <Media omitted>
4/29/24, 11:04 PM - Akshat Jain TMU: Hall
4/29/24, 11:04 PM - Akshat Jain TMU: Ko graph
4/29/24, 11:04 PM - Arpit Jain: <Media omitted>
4/29/24, 11:04 PM - Akshat Jain TMU: Bhi bhejdo
4/29/24, 11:04 PM - Arpit Jain: <Media omitted>
4/29/24, 11:04 PM - Akshat Jain TMU: This message was deleted
4/29/24, 11:04 PM - Arpit Jain: <Media omitted>
4/29/24, 11:05 PM - Akshat Jain TMU: Hall effect
4/29/24, 11:05 PM - Akshat Jain TMU: Ko graph
4/29/24, 11:05 PM - Arpit Jain: <Media omitted>
4/29/24, 11:06 PM - Akshat Jain TMU: 2 banane?
4/29/24, 11:07 PM - Arpit Jain: Haa
4/29/24, 11:07 PM - Akshat Jain TMU: Ok
4/29/24, 11:07 PM - Arpit Jain: Dusra wala complete karke bhej dena
4/29/24, 11:07 PM - Arpit Jain: Ok
4/29/24, 11:08 PM - Akshat Jain TMU: Ha
4/30/24, 5:23 PM - Akshat Jain TMU: Tumne error likho h ???
4/30/24, 5:23 PM - Akshat Jain TMU: Electrical me
4/30/24, 6:51 PM - Arpit Jain: Ha
4/30/24, 6:55 PM - Akshat Jain TMU: Bhejna
4/30/24, 7:28 PM - Akshat Jain TMU: Bhedo
4/30/24, 7:28 PM - Akshat Jain TMU: Bhejdo
5/1/24, 2:27 PM - Akshat Jain TMU: <Media omitted>
5/1/24, 2:27 PM - Akshat Jain TMU: <Media omitted>
5/1/24, 2:29 PM - Akshat Jain TMU: <Media omitted>
5/1/24, 6:33 PM - Arpit Jain: <Media omitted>
5/1/24, 6:33 PM - Arpit Jain: <Media omitted>
5/1/24, 6:33 PM - Arpit Jain: <Media omitted>
5/4/24, 10:43 AM - Akshat Jain TMU: <Media omitted>
5/5/24, 2:46 PM - Arpit Jain: <Media omitted>
5/5/24, 2:46 PM - Arpit Jain: <Media omitted>
5/5/24, 2:46 PM - Arpit Jain: <Media omitted>
5/5/24, 2:46 PM - Arpit Jain: <Media omitted>
5/5/24, 2:46 PM - Arpit Jain: <Media omitted>
5/5/24, 2:46 PM - Arpit Jain: <Media omitted>
5/10/24, 11:42 AM - Akshat Jain TMU: Electrical unit 4 and 5 ke notes h ??
5/10/24, 12:56 PM - Arpit Jain: 4 ke hai only
5/10/24, 12:59 PM - Akshat Jain TMU: Bhejdo
5/12/24, 10:18 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:18 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:18 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:18 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:18 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:18 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:18 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:18 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:18 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:18 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:18 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:18 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:18 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:18 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:19 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:19 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:19 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:19 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:19 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:19 PM - Akshat Jain TMU: <Media omitted>
5/12/24, 10:19 PM - Akshat Jain TMU: <Media omitted>
5/18/24, 11:39 PM - Akshat Jain TMU: Halls effect likho h tumai pass ???
5/18/24, 11:40 PM - Akshat Jain TMU: <Media omitted>
5/19/24, 1:25 AM - Arpit Jain: Nahi yaar
5/19/24, 1:26 AM - Akshat Jain TMU: Bhai dekho yr
5/19/24, 1:26 AM - Akshat Jain TMU: Hame ek doubt h
5/19/24, 1:26 AM - Arpit Jain: Ka
5/19/24, 1:26 AM - Akshat Jain TMU: Hall effect me theory theory jayada h
5/19/24, 1:26 AM - Akshat Jain TMU: Ya formula based h
5/19/24, 1:26 AM - Arpit Jain: To
5/19/24, 1:27 AM - Arpit Jain: Abe hamne 4 aur 5 unit nahi padhi
5/19/24, 1:27 AM - Arpit Jain: To pata nahi dekho
5/19/24, 1:27 AM - Akshat Jain TMU: Ok
5/19/24, 1:27 AM - Arpit Jain: Ok
6/4/24, 7:42 PM - Akshat Jain TMU: <Media omitted>
6/4/24, 7:42 PM - Akshat Jain TMU: <Media omitted>
8/25/24, 9:38 PM - Akshat Jain TMU: null
9/1/24, 2:34 PM - Akshat Jain TMU: <Media omitted>
9/1/24, 2:34 PM - Akshat Jain TMU: Le re lund ke
9/9/24, 10:53 AM - Arpit Jain: null
9/9/24, 10:53 AM - Arpit Jain: null
9/9/24, 10:55 AM - Akshat Jain TMU: null
9/9/24, 2:29 PM - Arpit Jain: null
9/10/24, 2:21 PM - Akshat Jain TMU: Apna chasma le jana
9/10/24, 2:21 PM - Akshat Jain TMU: Waaha table pe chor gai the tum
9/12/24, 9:37 PM - Arpit Jain: <Media omitted>
9/12/24, 9:42 PM - Arpit Jain: Bhej di
9/14/24, 6:26 PM - Akshat Jain TMU: Result
9/14/24, 6:26 PM - Akshat Jain TMU: ?
9/14/24, 6:30 PM - Arpit Jain: You deleted this message
9/14/24, 6:38 PM - Arpit Jain: <Media omitted>
9/14/24, 7:13 PM - Akshat Jain TMU: Chode ke
9/14/24, 7:13 PM - Akshat Jain TMU: Tumhe password kine batao
9/14/24, 7:44 PM - Arpit Jain: Jaadu
9/27/24, 11:39 AM - Arpit Jain: <Media omitted>
9/27/24, 2:14 PM - Akshat Jain TMU: 24485111
9/27/24, 2:26 PM - Arpit Jain: You deleted this message
10/11/24, 10:12 PM - Akshat Jain TMU: Sabhi codes dekhlo
10/11/24, 10:12 PM - Akshat Jain TMU: <Media omitted>
10/11/24, 10:12 PM - Akshat Jain TMU: <Media omitted>
10/11/24, 10:12 PM - Akshat Jain TMU: <Media omitted>
10/11/24, 10:22 PM - Arpit Jain: Pehla wala sahi hai Dusre me int* , int* hai
10/11/24, 10:22 PM - Arpit Jain: Teesra bhi sahi hai
10/11/24, 11:35 PM - Akshat Jain TMU: first me int x int y hoga ya int a int b hoga
10/12/24, 9:07 AM - Arpit Jain: Sahi hai
10/12/24, 9:07 AM - Arpit Jain: Jo hai usme
10/12/24, 9:42 AM - Akshat Jain TMU: Ka
10/12/24, 9:42 AM - Akshat Jain TMU: Jo?
10/12/24, 9:42 AM - Arpit Jain: Jesa hai
10/12/24, 9:44 AM - Arpit Jain: ẞñçä
11/7/24, 3:00 PM - Akshat Jain TMU: create table customer1(Cus_id int, Cus_Name varchar(30), Ref_id int, Prod_id int,
Date_of_purchase date, Price int, Discount int, primary key(Cus_id))
11/7/24, 3:00 PM - Akshat Jain TMU: create table Product(Prod_id int primary key, Prod_category varchar(20))
 desc customer1
11/7/24, 3:00 PM - Akshat Jain TMU: insert all
 into customer values(1359, 'Elina Taylor', 1608, 20,'05-OCT-2006', 1000)
 into customer values(1573, 'Mark Lyon', 1175, 40,'05-SEP-2008', 1550, 110)
 into customer values(1932, 'Stuart Twain', 1608, 60,'23-AUG-2009', 3000, 230)
 into customer values(1875, 'Allan Samuels', 1610, 80,'15-NOV-2011', 10000, 970)
 into customer values(1723, 'Peter Russel', '', 40,'17-JUL-2010', 4000, 250)
 into customer values(1973, 'Andre Finch', 1932, 60,'12-MAR-2014', 6000, 530)
 into customer values(1205, 'Steffi Nicolus', 1175, 20,'07-FEB-2012', 1500, '')
 into customer values(1608, 'Adams Franklin', ' ', 80,'05-JAN-2010', 8000, 530)
 into customer values(1175, 'Luke Martin', 1932, 60,'14-DEC-2007', 3500, 300)
 into customer values(1097, 'Joseph Milne', 1610, 40,'07-APR-2007', 1200, 80)
 into customer values(1850, 'Mary Roberts', 1875, 20,'12-SEP-2008', 1170, '')
 into customer values(1610, 'Sheldon Moris', 1175, 80,'08-MAY-2009', 11050, 915)
 select * from dual
11/7/24, 3:02 PM - Akshat Jain TMU: insert all
 into Product values(20,'Cosmetics')
 into Product values(40,'Daily Needs')
 into Product values(60,'Garments')
 into Product values(80,'Equipment')
 select * from Dual
11/7/24, 7:54 PM - Akshat Jain TMU: <Media omitted>
11/14/24, 9:05 PM - Arpit Jain: <Media omitted>
11/16/24, 2:03 AM - Akshat Jain TMU: Or likhe ??
11/20/24, 1:09 PM - Akshat Jain TMU: Bhai exam fees jama krdi ?
11/20/24, 1:34 PM - Akshat Jain TMU: Mere me cash rakha h
11/20/24, 1:43 PM - Arpit Jain: Abhi nahi ki
11/20/24, 1:53 PM - Akshat Jain TMU: Kabe kro
11/20/24, 1:54 PM - Arpit Jain: Ct ke baad
11/20/24, 1:54 PM - Akshat Jain TMU: Hao
11/20/24, 7:55 PM - Akshat Jain TMU: Bhai DE me kuch important topic bata do jo ct me aa skte h
11/20/24, 10:06 PM - Arpit Jain: Stack , counter ,flip flop
11/20/24, 10:06 PM - Arpit Jain: Iske bahar kuch nahi
11/20/24, 11:19 PM - Arpit Jain: You deleted this message
11/20/24, 11:19 PM - Arpit Jain: You deleted this message
11/20/24, 11:19 PM - Arpit Jain: You deleted this message
11/20/24, 11:19 PM - Arpit Jain: You deleted this message
11/20/24, 11:19 PM - Arpit Jain: You deleted this message
11/20/24, 11:19 PM - Arpit Jain: You deleted this message
11/20/24, 11:19 PM - Arpit Jain: You deleted this message
11/20/24, 11:19 PM - Arpit Jain: You deleted this message
11/20/24, 11:35 PM - Arpit Jain: <Media omitted>
11/20/24, 11:36 PM - Arpit Jain: <Media omitted>
11/20/24, 11:36 PM - Arpit Jain: <Media omitted>
11/20/24, 11:36 PM - Arpit Jain: <Media omitted>
11/20/24, 11:37 PM - Arpit Jain: <Media omitted>
11/20/24, 11:37 PM - Arpit Jain: <Media omitted>
11/20/24, 11:37 PM - Arpit Jain: <Media omitted>
11/20/24, 11:37 PM - Arpit Jain: <Media omitted>

In [4]:
pattern = r'\d{1,2}/\d{1,2}/\d{2},\s\d{1,2}:\d{2}\s-\s'

In [7]:
messages = re.split(pattern, data_cleaned)[1:]
messages

['Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. Learn more.\n',
 'Akshat Jain TMU is a contact\n',
 'Akshat Jain TMU: Hi\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: Bhai m ne jo kal likhaya tha bo semd kro do\n',
 'Akshat Jain TMU: Chemistry\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: Done\n',
 'Akshat Jain TMU: Hao\n',
 'Akshat Jain TMU: Thanks\n',
 'Arpit Jain: 👍\n',
 'Akshat Jain TMU: Iske aage ka send kro\n',
 'Akshat Jain TMU: Flash and fire tk\n',
 'Arpit Jain: Hlo\n',
 'Arpit Jain: You deleted this message\n',
 'Arpit Jain: Kal aur parso jo ka hua hai class me vo send kar do\n',
 'Akshat Jain TMU: Bhai me khud collage nhi gaya\n',
 'Akshat Jain TMU: Gahr pe hu\n',
 'Arpit Jain: Are tum 8 ko gaye the\n',
 'Arpit Jain: 7 aur 6 ke bhej do\n',
 'Arpit Jain: Yaar\n',
 'Akshat Jain TMU: Ha\n',
 'Arpit Jain: You deleted this message\n',
 'Arpit Jain: To send kar do\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Arpit Jain: Ok\n',
 'Akshat Jain TMU: Kya ok\n',
 'Akshat Jain TMU: Print kya karwana English me\n',
 'Akshat Jain TMU: Batao\n',
 'Arpit Jain: Jo m ne pdf bheji hai group me English communication bale vo print karani hai\n',
 'Arpit Jain: Ok\n',
 'Akshat Jain TMU: Sari\n',
 'Akshat Jain TMU: Karani\n',
 'Arpit Jain: Ha sari\n',
 'Akshat Jain TMU: Ok\n',
 'Arpit Jain: Ok\n',
 'Akshat Jain TMU: Or sequence\n',
 'Akshat Jain TMU: Kesa kya rkhna\n',
 'Arpit Jain: Syllabus ke hisab se\n',
 'Akshat Jain TMU: Tumai total kitne page the\n',
 'Arpit Jain: 65\n',
 'Arpit Jain: Hai\n',
 'Akshat Jain TMU: Tum he bhejdo\n',
 'Akshat Jain TMU: Konsi karani\n',
 'Arpit Jain: Ok\n',
 'Arpit Jain: Abi bhej rahe ok\n',
 'Akshat Jain TMU: Pdf bhejdo\n',
 'Akshat Jain TMU: Konse karane\n',
 'Arpit Jain: Ok\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: Ok\n',
 'Akshat Jain TMU: null\n',
 'Arpit Jain: null\n',
 'Akshat Jain TMU: null\n',
 'Arpit Jain: null\n',
 'Arpit Jain: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: null\n',
 'Akshat Jain TMU: Tumao\n',
 'Akshat Jain TMU: Phone\n',
 'Akshat Jain TMU: Kai\n',
 'Akshat Jain TMU: Nhi\n',
 'Akshat Jain TMU: Lagt\n',
 'Akshat Jain TMU: ???\n',
 'Akshat Jain TMU: Or mess chal rai ???\n',
 'Arpit Jain: Nahi\n',
 'Arpit Jain: Mai 9 30 PE jauga\n',
 'Arpit Jain: Ok\n',
 'Akshat Jain TMU: Hao\n',
 'Akshat Jain TMU: H khaa aye\n',
 'Arpit Jain: Aaj nahi gaye khane\n',
 'Akshat Jain TMU: H kha ke agai\n',
 'Arpit Jain: Nahi Aaj nahi khaya sach me\n',
 'Arpit Jain: Ok\n',
 'Arpit Jain: Bhukh lag Rahi aab to\n',
 'Akshat Jain TMU: Ajao\n',
 'Akshat Jain TMU: Nasta kha lo mere room oe\n',
 'Arpit Jain: Are nahi\n',
 'Arpit Jain: Nahi\n',
 'Akshat Jain TMU: Tumao phone kai nhi lagt h\n',
 'Akshat Jain TMU: Incoming seva band ati h\n',
 'Arpit Jain: Are 9753939532 pe lagao lag Jago\n',
 'Arpit Jain: Ok\n',
 'Arpit Jain: Done\n',
 'Akshat Jain TMU: null\n',
 'Akshat Jain TMU: Kal\n',
 'Akshat Jain TMU: Auditorium chalne\n',
 'Akshat Jain TMU: Road safety\n',
 'Akshat Jain TMU: Balao ko\n',
 'Akshat Jain TMU: 2 baje\n',
 'Arpit Jain: Ok\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: Hlo\n',
 'Arpit Jain: Hlo\n',
 'Arpit Jain: Are you there\n',
 'Arpit Jain: Hlo\n',
 'Arpit Jain: Response me\n',
 'Arpit Jain: Hlo\n',
 'Arpit Jain: Hlo\n',
 'Akshat Jain TMU: Haaa\n',
 'Akshat Jain TMU: Bolo\n',
 'Akshat Jain TMU: Ka h\n',
 'Akshat Jain TMU: Bolo ab\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: Kitne baje tk jo\n',
 'Akshat Jain TMU: ??\n',
 'Arpit Jain: 9\n',
 'Arpit Jain: Baje\n',
 'Akshat Jain TMU: Abhi kya kar rai\n',
 'Akshat Jain TMU: Bhai physics ke notes dedo yr\n',
 'Akshat Jain TMU: Chalo\n',
 'Akshat Jain TMU: Chalo\n',
 'Akshat Jain TMU: Chalo\n',
 'Akshat Jain TMU: Halo\n',
 'Akshat Jain TMU: Chalo\n',
 'Akshat Jain TMU: Chalo\n',
 'Akshat Jain TMU: Chalo\n',
 'Akshat Jain TMU: Halo\n',
 'Akshat Jain TMU: Halo\n',
 'Akshat Jain TMU: Halo\n',
 'Akshat Jain TMU: Halo\n',
 'Akshat Jain TMU: Halo\n',
 'Arpit Jain: Heeeeee\n',
 'Arpit Jain: Haaaaaa\n',
 'Arpit Jain: Hooooo\n',
 'Arpit Jain: Op bolte\n',
 'Arpit Jain: Ok\n',
 'Akshat Jain TMU: Do\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: Mandir jaoge ??\n',
 'Arpit Jain: Ha ha\n',
 'Arpit Jain: Ha\n',
 'Akshat Jain TMU: Physics important question\n1- Discuss the प्रिंसिपल ऑफ superposition derive the expressuon for the resultant intensity and discuss the condition for maxima and minima (10 marks) \n2- obtain the path difference in fresnel biprism and drive the expression for the fringe width and so that fringe width are dark and bright. \n3- discuss the method to determine the wavelength of  a monochromatic source using fresnel biprism\n4-Derice the expression for path differnece in a thin film of uniform thickness using reflected or transmitted light and  discuss the conditon for maxima\n',
 'Akshat Jain TMU: Method batabe\n',
 'Akshat Jain TMU: Batane\n',
 'Akshat Jain TMU: 3rd bala\n',
 'Akshat Jain TMU: Bolooooooooooooooooooooo\n',
 'Arpit Jain: Are muje nahi pata mene to abhi suna ye\n',
 'Arpit Jain: Are sahi mai\n',
 'Akshat Jain TMU: Bhai pls bata do\n',
 'Akshat Jain TMU: Na tmne math baatai\n',
 'Akshat Jain TMU: Math me bhi chud gai\n',
 'Arpit Jain: Math to hao bhi long ko galat ho gayo\n',
 'Arpit Jain: Patahe\n',
 'Arpit Jain: Tumne batao\n',
 'Akshat Jain TMU: H tumai room pe aa rai\n',
 'Arpit Jain: Kachu math mai\n',
 'Akshat Jain TMU: He bata do\n',
 'Akshat Jain TMU: 3rd balo\n',
 'Akshat Jain TMU: Santi se\n',
 'Arpit Jain: Aa jao hum to ja rahe khana khane\n',
 'Arpit Jain: Hiiiiiiiiii\n',
 'Akshat Jain TMU: To kahana kha ke hai room pe ajaio\n',
 'Arpit Jain: Byyyyyyyyyyyyyyyyyy\n',
 'Akshat Jain TMU: Nooo\n',
 'Akshat Jain TMU: Ruko\n',
 'Arpit Jain: Ok\n',
 'Akshat Jain TMU: Wait\n',
 'Arpit Jain: Ok\n',
 'Arpit Jain: Hahahahahahahha\n',
 'Akshat Jain TMU: Mere room pe aja a\n',
 'Arpit Jain: Ha\n',
 'Akshat Jain TMU: Mujhe bata dena thodi\n',
 'Akshat Jain TMU: 1-2 doubt h\n',
 'Arpit Jain: Aada ghante Mai ok\n',
 'Akshat Jain TMU: Clear kardena bass\n',
 'Akshat Jain TMU: Ok\n',
 'Arpit Jain: Ok\n',
 'Arpit Jain: Byyyyy\n',
 'Akshat Jain TMU: 😚\n',
 'Akshat Jain TMU: Bye\n',
 'Akshat Jain TMU: Sweet heart 💕\n',
 'Arpit Jain: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: Kai tum hai drawing bai pencil lai ka\n',
 'Arpit Jain: Nai to\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: Hi\n',
 'Akshat Jain TMU: +91 83848 26047\n',
 'Akshat Jain TMU: Bhejdo\n',
 'Arpit Jain: Hao\n',
 'Arpit Jain: Bhej dae\n',
 'Arpit Jain: Ok\n',
 'Akshat Jain TMU: Ha\n',
 'Arpit Jain: Sare nahi ja rahe\n',
 'Akshat Jain TMU: Mene bhej diye\n',
 'Akshat Jain TMU: Rhne do\n',
 'Akshat Jain TMU: Net ka problem ho raha tha\n',
 'Akshat Jain TMU: Ab chalne laga\n',
 'Akshat Jain TMU: Btw thanks\n',
 'Arpit Jain: Ok\n',
 'Akshat Jain TMU: Electrical ki unit 4 me kaha tk padhna h ??\n',
 'Arpit Jain: Pura padna hai\n',
 'Akshat Jain TMU: Newton rings\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: Ek introduction ka page hoga or ek thankyou bala\n',
 'Akshat Jain TMU: Apne hisab se ek page choice karlo konsa bologe \nBohi bol dena \nThoda sa hi bolna h jayda nhi\n',
 'Arpit Jain: Pehle dono me se ek karlo\n',
 'Arpit Jain: Vo achhe hai\n',
 'Akshat Jain TMU: Matlb\n',
 'Akshat Jain TMU: Are 5 log bolege\n',
 'Akshat Jain TMU: To ek ek boldo\n',
 'Akshat Jain TMU: Tum \nH \nArpit cr\n',
 'Akshat Jain TMU: 3 confirm h\n',
 'Arpit Jain: Achhaa\n',
 'Akshat Jain TMU: 2 or chane\n',
 'Akshat Jain TMU: Bo aryan Mishra ki bol raha tha\n',
 'Akshat Jain TMU: Uska abhi confirm nhi h\n',
 'Akshat Jain TMU: Puch ke batunga\n',
 'Arpit Jain: To me dusra bol dunga\n',
 'Arpit Jain: Thike\n',
 'Akshat Jain TMU: Ok\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Akshat Jain TMU: Hall\n',
 'Akshat Jain TMU: Ko graph\n',
 'Arpit Jain: <Media omitted>\n',
 'Akshat Jain TMU: Bhi bhejdo\n',
 'Arpit Jain: <Media omitted>\n',
 'Akshat Jain TMU: This message was deleted\n',
 'Arpit Jain: <Media omitted>\n',
 'Akshat Jain TMU: Hall effect\n',
 'Akshat Jain TMU: Ko graph\n',
 'Arpit Jain: <Media omitted>\n',
 'Akshat Jain TMU: 2 banane?\n',
 'Arpit Jain: Haa\n',
 'Akshat Jain TMU: Ok\n',
 'Arpit Jain: Dusra wala complete karke bhej dena\n',
 'Arpit Jain: Ok\n',
 'Akshat Jain TMU: Ha\n',
 'Akshat Jain TMU: Tumne error likho h ???\n',
 'Akshat Jain TMU: Electrical me\n',
 'Arpit Jain: Ha\n',
 'Akshat Jain TMU: Bhejna\n',
 'Akshat Jain TMU: Bhedo\n',
 'Akshat Jain TMU: Bhejdo\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Akshat Jain TMU: Electrical unit 4 and 5 ke notes h ??\n',
 'Arpit Jain: 4 ke hai only\n',
 'Akshat Jain TMU: Bhejdo\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: Halls effect likho h tumai pass ???\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Arpit Jain: Nahi yaar\n',
 'Akshat Jain TMU: Bhai dekho yr\n',
 'Akshat Jain TMU: He ek doubt h\n',
 'Arpit Jain: Ka\n',
 'Akshat Jain TMU: Hall effect me theory theory jayada h\n',
 'Akshat Jain TMU: Ya formula based h\n',
 'Arpit Jain: To\n',
 'Arpit Jain: Abe hne 4 aur 5 unit nahi padhi\n',
 'Arpit Jain: To pata nahi dekho\n',
 'Akshat Jain TMU: Ok\n',
 'Arpit Jain: Ok\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: null\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: Le re lund ke\n',
 'Arpit Jain: null\n',
 'Arpit Jain: null\n',
 'Akshat Jain TMU: null\n',
 'Arpit Jain: null\n',
 'Akshat Jain TMU: Apna chasma le jana\n',
 'Akshat Jain TMU: Waaha table pe chor gai the tum\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: Bhej di\n',
 'Akshat Jain TMU: Result\n',
 'Akshat Jain TMU: ?\n',
 'Arpit Jain: You deleted this message\n',
 'Arpit Jain: <Media omitted>\n',
 'Akshat Jain TMU: Chode ke\n',
 'Akshat Jain TMU: Tumhe password kine batao\n',
 'Arpit Jain: Jaadu\n',
 'Arpit Jain: <Media omitted>\n',
 'Akshat Jain TMU: 24485111\n',
 'Arpit Jain: You deleted this message\n',
 'Akshat Jain TMU: Sabhi codes dekhlo\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Arpit Jain: Pehla wala sahi hai Dusre me int* , int* hai\n',
 'Arpit Jain: Teesra bhi sahi hai\n',
 'Akshat Jain TMU: first me int x int y hoga ya int a int b hoga\n',
 'Arpit Jain: Sahi hai\n',
 'Arpit Jain: Jo hai usme\n',
 'Akshat Jain TMU: Ka\n',
 'Akshat Jain TMU: Jo?\n',
 'Arpit Jain: Jesa hai\n',
 'Arpit Jain: ẞñçä\n',
 'Akshat Jain TMU: create table customer1(Cus_id int, Cus_Ne varchar(30), Ref_id int, Prod_id int, \nDate_of_purchase date, Price int, Discount int, primary key(Cus_id))\n',
 'Akshat Jain TMU: create table Product(Prod_id int primary key, Prod_category varchar(20))\n desc customer1\n',
 "Akshat Jain TMU: insert all\n into customer values(1359, 'Elina Taylor', 1608, 20,'05-OCT-2006', 1000)\n into customer values(1573, 'Mark Lyon', 1175, 40,'05-SEP-2008', 1550, 110)\n into customer values(1932, 'Stuart Twain', 1608, 60,'23-AUG-2009', 3000, 230)\n into customer values(1875, 'Allan Suels', 1610, 80,'15-NOV-2011', 10000, 970)\n into customer values(1723, 'Peter Russel', '', 40,'17-JUL-2010', 4000, 250)\n into customer values(1973, 'Andre Finch', 1932, 60,'12-MAR-2014', 6000, 530)\n into customer values(1205, 'Steffi Nicolus', 1175, 20,'07-FEB-2012', 1500, '')\n into customer values(1608, 'Ads Franklin', ' ', 80,'05-JAN-2010', 8000, 530)\n into customer values(1175, 'Luke Martin', 1932, 60,'14-DEC-2007', 3500, 300)\n into customer values(1097, 'Joseph Milne', 1610, 40,'07-APR-2007', 1200, 80)\n into customer values(1850, 'Mary Roberts', 1875, 20,'12-SEP-2008', 1170, '')\n into customer values(1610, 'Sheldon Moris', 1175, 80,'08-MAY-2009', 11050, 915)\n select * from dual\n",
 "Akshat Jain TMU: insert all\n into Product values(20,'Cosmetics')\n into Product values(40,'Daily Needs')\n into Product values(60,'Garments')\n into Product values(80,'Equient')\n select * from Dual\n",
 'Akshat Jain TMU: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Akshat Jain TMU: Or likhe ??\n',
 'Akshat Jain TMU: Bhai ex fees ja krdi ?\n',
 'Akshat Jain TMU: Mere me cash rakha h\n',
 'Arpit Jain: Abhi nahi ki\n',
 'Akshat Jain TMU: Kabe kro\n',
 'Arpit Jain: Ct ke baad\n',
 'Akshat Jain TMU: Hao\n',
 'Akshat Jain TMU: Bhai DE me kuch important topic bata do jo ct me aa skte h\n',
 'Arpit Jain: Stack , counter ,flip flop\n',
 'Arpit Jain: Iske bahar kuch nahi\n',
 'Arpit Jain: You deleted this message\n',
 'Arpit Jain: You deleted this message\n',
 'Arpit Jain: You deleted this message\n',
 'Arpit Jain: You deleted this message\n',
 'Arpit Jain: You deleted this message\n',
 'Arpit Jain: You deleted this message\n',
 'Arpit Jain: You deleted this message\n',
 'Arpit Jain: You deleted this message\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Akshat Jain TMU: Bhai\n',
 'Akshat Jain TMU: Math bhi padha do\n',
 'Akshat Jain TMU: Ajj ko ct tumai bajh se accho chalo gao\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: null\n',
 'Arpit Jain: null\n',
 'Akshat Jain TMU: Attendance nhi li\n',
 'Arpit Jain: You deleted this message\n',
 'Arpit Jain: Ok\n',
 'Arpit Jain: Thank you yaar\n',
 'Arpit Jain: import mysql.connector\n\n# Establish a connection to the database\nconn = mysql.connector.connect(\n    host="localhost",      # Your MySQL server address (localhost for local MySQL server)\n    user="root",           # Your MySQL userne\n    password="password",   # Your MySQL password\n    database="test_db"     # Ne of the database you want to connect to\n)\n\n# Create a cursor object using the connection\ncursor = conn.cursor()\n\n# Exple query to fetch all records from a table\ncursor.execute("SELECT * FROM users")\n\n# Fetch all results from the query\nresult = cursor.fetchall()\n\n# Print the results\nfor row in result:\n    print(row)\n\n# Don\'t forget to close the cursor and connection when done\ncursor.close()\nconn.close()\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 "Akshat Jain TMU: *Internship Batch*\n\nNew batches with guidance from *IITs and IIMs* for *Internships* are open with  guidance from Industrial experts are now open in Acmegrade.\n\n♾️Experts and alumni's at *Ssung,azon, Toyota,  Tata, and many more*\n\n♾️ *Certifications, LORs, Stipend* and *Placement* Guidance.\n\n♾️ *Free Internships with stipend starting from Rs 15000*\n\n*All Interested Candidates can Join the Official WhatsApp Group through the link attached below.*\nhttps://chat.whatsapp.com/BVDlrUTmKBXHSEdbJmetmD\n\n\n*NOTE*: This will not clash with your classes/exs.\n\n*Circulate with all your friends andbitious candidates*\n",
 'Akshat Jain TMU: Join krdo bhai members badhane h\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: https://docs.google.com/forms/d/e/1FAIpQLScY7ZXBF4-28AB6rULBrQbsM5GFlsoRUoUJV0cn4iqK2WJAtQ/viewform?usp=sharing\n',
 'Akshat Jain TMU: Pahle hi bhar diya\n',
 'Arpit Jain: Ok\n',
 'Arpit Jain: Dobara bar do\n',
 'Akshat Jain TMU: Ok\n',
 'Arpit Jain: Frohes Neues Jahr\n',
 'Arpit Jain: bonne année\n',
 'Akshat Jain TMU: Bhai ek doubt h thoda\n',
 'Akshat Jain TMU: Call by value reference and address me\n',
 'Arpit Jain: Kya achhi baat hai doubt hona\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Arpit Jain: Are ye upar wala mat likho pir bhi chal jayega\n',
 'Arpit Jain: Ek line\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: Konsi line\n',
 'Akshat Jain TMU: Voud swap bali ??\n',
 'Arpit Jain: Ye hi jo tum bhej rahe ho\n',
 'Akshat Jain TMU: Void*\n',
 'Arpit Jain: Ha\n',
 'Akshat Jain TMU: Theek h\n',
 'Akshat Jain TMU: Dhanyawad Bhai\n',
 'Arpit Jain: Lekin jo main ke neeche hai vo sara main ke uper likhna\n',
 'Arpit Jain: Bas\n',
 'Akshat Jain TMU: Mtlb\n',
 'Akshat Jain TMU: Bhai tum ek page pe likh do\n',
 'Akshat Jain TMU: Value reference and address\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Arpit Jain: Return 0 ke baad jo bhi neeche hai use uper likh do\n',
 'Akshat Jain TMU: Accha\n',
 'Akshat Jain TMU: Theek h\n',
 'Akshat Jain TMU: Ok\n',
 'Arpit Jain: Ok\n',
 'Akshat Jain TMU: Sbhu ka assignment ke qts send kardo\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: Result aa gaya tumara\n',
 'Akshat Jain TMU: Tumao ??\n',
 'Arpit Jain: Bhai back aa gayi meri\n',
 'Arpit Jain: <Media omitted>\n',
 'Arpit Jain: 🥹\n',
 'Akshat Jain TMU: 8.5\n',
 'Akshat Jain TMU: Santosh\n',
 'Arpit Jain: Bsdk tuje kese pata\n',
 'Akshat Jain TMU: Jese tumne dekha\n',
 'Arpit Jain: null\n',
 'Akshat Jain TMU: <Media omitted>\n',
 'Akshat Jain TMU: null\n',
 'Akshat Jain TMU: null\n',
 'Akshat Jain TMU: null\n',
 'Arpit Jain: null\n',
 'Akshat Jain TMU: null\n',
 'Akshat Jain TMU: null\n',
 'Akshat Jain TMU: null\n',
 'Arpit Jain: null\n',
 'Akshat Jain TMU: Previous year ke Cts send krdo\n',
 'Akshat Jain TMU: null\n',
 'Akshat Jain TMU: null\n',
 'Arpit Jain: null\n',
 'Arpit Jain: null\n',
 'Arpit Jain: <Media omitted>\n',
 'Akshat Jain TMU: null\n',
 'Akshat Jain TMU: null\n',
 'Akshat Jain TMU: null\n',
 'Akshat Jain TMU: hii bro\n',
 'Akshat Jain TMU: are you awake??\n',
 'Akshat Jain TMU: can you tell me what we need to study in heuristic search\n',
 'Arpit Jain: sure why not\n',
 'Akshat Jain TMU: yes so what we need to study\n',

In [8]:
dates = re.findall(pattern, data_cleaned)
dates

['9/7/23, 9:21 - ',
 '10/10/23, 12:32 - ',
 '10/10/23, 12:32 - ',
 '10/10/23, 12:32 - ',
 '10/31/23, 9:06 - ',
 '10/31/23, 9:07 - ',
 '10/31/23, 10:02 - ',
 '10/31/23, 10:03 - ',
 '10/31/23, 10:43 - ',
 '10/31/23, 10:47 - ',
 '10/31/23, 10:47 - ',
 '10/31/23, 11:29 - ',
 '11/3/23, 11:19 - ',
 '11/3/23, 11:19 - ',
 '11/9/23, 3:37 - ',
 '11/9/23, 3:38 - ',
 '11/9/23, 3:38 - ',
 '11/9/23, 3:43 - ',
 '11/9/23, 3:43 - ',
 '11/9/23, 3:44 - ',
 '11/9/23, 3:45 - ',
 '11/9/23, 3:45 - ',
 '11/9/23, 4:16 - ',
 '11/9/23, 6:24 - ',
 '11/9/23, 6:30 - ',
 '11/9/23, 8:53 - ',
 '11/9/23, 8:53 - ',
 '11/9/23, 8:53 - ',
 '11/9/23, 8:53 - ',
 '11/24/23, 8:36 - ',
 '11/24/23, 8:45 - ',
 '2/13/24, 4:11 - ',
 '2/13/24, 4:11 - ',
 '2/13/24, 4:15 - ',
 '2/13/24, 4:15 - ',
 '2/13/24, 4:15 - ',
 '2/13/24, 4:15 - ',
 '2/13/24, 4:15 - ',
 '2/13/24, 4:15 - ',
 '2/13/24, 4:15 - ',
 '2/13/24, 4:15 - ',
 '2/13/24, 4:15 - ',
 '2/13/24, 4:16 - ',
 '2/13/24, 4:17 - ',
 '2/13/24, 4:17 - ',
 '2/13/24, 4:17 - ',
 '2/13/24, 4:17 - ',
 '2/13/24, 4:17 - ',
 '2/13/24, 4:18 - ',
 '2/13/24, 4:19 - ',
 '2/13/24, 4:19 - ',
 '2/13/24, 4:19 - ',
 '2/13/24, 4:19 - ',
 '2/13/24, 4:19 - ',
 '2/13/24, 4:19 - ',
 '2/13/24, 4:19 - ',
 '2/13/24, 4:19 - ',
 '2/13/24, 4:19 - ',
 '2/13/24, 4:19 - ',
 '2/13/24, 4:19 - ',
 '2/13/24, 4:19 - ',
 '2/13/24, 4:21 - ',
 '2/22/24, 2:18 - ',
 '2/22/24, 2:19 - ',
 '2/22/24, 2:22 - ',
 '2/22/24, 2:26 - ',
 '2/22/24, 3:07 - ',
 '2/22/24, 3:34 - ',
 '2/22/24, 8:37 - ',
 '2/22/24, 8:37 - ',
 '2/22/24, 8:37 - ',
 '2/22/24, 8:37 - ',
 '2/22/24, 8:37 - ',
 '2/22/24, 8:37 - ',
 '2/22/24, 8:37 - ',
 '2/22/24, 8:37 - ',
 '2/22/24, 9:03 - ',
 '2/22/24, 9:03 - ',
 '2/22/24, 9:03 - ',
 '2/22/24, 9:07 - ',
 '2/22/24, 9:07 - ',
 '2/22/24, 10:08 - ',
 '2/22/24, 10:08 - ',
 '2/22/24, 10:19 - ',
 '2/22/24, 10:19 - ',
 '2/22/24, 10:20 - ',
 '2/22/24, 10:30 - ',
 '2/22/24, 10:30 - ',
 '2/22/24, 10:58 - ',
 '2/22/24, 10:58 - ',
 '2/22/24, 11:16 - ',
 '2/22/24, 11:16 - ',
 '2/23/24, 8:15 - ',
 '2/23/24, 8:15 - ',
 '2/23/24, 8:16 - ',
 '2/23/24, 8:52 - ',
 '2/23/24, 3:16 - ',
 '2/23/24, 3:16 - ',
 '2/23/24, 3:16 - ',
 '2/23/24, 3:16 - ',
 '2/23/24, 3:16 - ',
 '2/23/24, 4:05 - ',
 '2/24/24, 11:34 - ',
 '2/26/24, 4:06 - ',
 '2/26/24, 4:06 - ',
 '2/26/24, 4:06 - ',
 '2/26/24, 4:07 - ',
 '2/26/24, 4:07 - ',
 '2/26/24, 4:07 - ',
 '2/26/24, 4:07 - ',
 '2/26/24, 4:44 - ',
 '2/26/24, 4:44 - ',
 '2/26/24, 5:24 - ',
 '2/26/24, 5:24 - ',
 '2/27/24, 2:30 - ',
 '2/28/24, 8:25 - ',
 '2/28/24, 8:25 - ',
 '2/28/24, 8:27 - ',
 '2/28/24, 8:27 - ',
 '2/28/24, 8:28 - ',
 '2/28/24, 8:29 - ',
 '2/28/24, 8:59 - ',
 '2/28/24, 8:59 - ',
 '2/28/24, 8:59 - ',
 '2/28/24, 8:59 - ',
 '2/28/24, 8:59 - ',
 '2/28/24, 8:59 - ',
 '2/28/24, 8:59 - ',
 '2/28/24, 8:59 - ',
 '2/28/24, 8:59 - ',
 '2/28/24, 8:59 - ',
 '2/28/24, 8:59 - ',
 '2/28/24, 8:59 - ',
 '2/28/24, 11:16 - ',
 '2/28/24, 11:16 - ',
 '2/28/24, 11:16 - ',
 '2/28/24, 11:17 - ',
 '2/28/24, 11:17 - ',
 '2/28/24, 11:24 - ',
 '2/29/24, 9:58 - ',
 '2/29/24, 12:41 - ',
 '3/2/24, 5:47 - ',
 '3/2/24, 8:56 - ',
 '3/2/24, 8:56 - ',
 '3/4/24, 9:50 - ',
 '3/4/24, 9:51 - ',
 '3/4/24, 9:51 - ',
 '3/4/24, 9:51 - ',
 '3/4/24, 9:52 - ',
 '3/4/24, 9:53 - ',
 '3/4/24, 9:53 - ',
 '3/4/24, 9:53 - ',
 '3/4/24, 9:53 - ',
 '3/4/24, 9:53 - ',
 '3/4/24, 9:53 - ',
 '3/4/24, 9:53 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:54 - ',
 '3/4/24, 9:55 - ',
 '3/4/24, 9:55 - ',
 '3/4/24, 9:55 - ',
 '3/4/24, 9:55 - ',
 '3/4/24, 9:55 - ',
 '3/4/24, 9:55 - ',
 '3/4/24, 9:55 - ',
 '3/4/24, 9:55 - ',
 '3/4/24, 9:55 - ',
 '3/4/24, 9:55 - ',
 '4/5/24, 12:18 - ',
 '4/6/24, 11:31 - ',
 '4/6/24, 5:20 - ',
 '4/6/24, 6:46 - ',
 '4/6/24, 7:32 - ',
 '4/6/24, 7:32 - ',
 '4/6/24, 7:32 - ',
 '4/6/24, 7:34 - ',
 '4/6/24, 7:34 - ',
 '4/6/24, 7:35 - ',
 '4/6/24, 7:35 - ',
 '4/6/24, 7:35 - ',
 '4/8/24, 7:50 - ',
 '4/8/24, 7:50 - ',
 '4/8/24, 7:52 - ',
 '4/8/24, 7:52 - ',
 '4/8/24, 7:55 - ',
 '4/8/24, 7:55 - ',
 '4/8/24, 7:56 - ',
 '4/8/24, 7:57 - ',
 '4/8/24, 7:57 - ',
 '4/8/24, 7:57 - ',
 '4/8/24, 7:58 - ',
 '4/8/24, 7:58 - ',
 '4/8/24, 7:58 - ',
 '4/8/24, 10:16 - ',
 '4/20/24, 8:12 - ',
 '4/22/24, 8:22 - ',
 '4/29/24, 4:50 - ',
 '4/29/24, 7:23 - ',
 '4/29/24, 7:32 - ',
 '4/29/24, 7:33 - ',
 '4/29/24, 7:40 - ',
 '4/29/24, 7:40 - ',
 '4/29/24, 7:40 - ',
 '4/29/24, 7:41 - ',
 '4/29/24, 7:41 - ',
 '4/29/24, 7:41 - ',
 '4/29/24, 7:41 - ',
 '4/29/24, 7:41 - ',
 '4/29/24, 7:41 - ',
 '4/29/24, 7:41 - ',
 '4/29/24, 7:41 - ',
 '4/29/24, 7:41 - ',
 '4/29/24, 7:43 - ',
 '4/29/24, 7:43 - ',
 '4/29/24, 7:43 - ',
 '4/29/24, 11:03 - ',
 '4/29/24, 11:04 - ',
 '4/29/24, 11:04 - ',
 '4/29/24, 11:04 - ',
 '4/29/24, 11:04 - ',
 '4/29/24, 11:04 - ',
 '4/29/24, 11:04 - ',
 '4/29/24, 11:04 - ',
 '4/29/24, 11:04 - ',
 '4/29/24, 11:05 - ',
 '4/29/24, 11:05 - ',
 '4/29/24, 11:05 - ',
 '4/29/24, 11:06 - ',
 '4/29/24, 11:07 - ',
 '4/29/24, 11:07 - ',
 '4/29/24, 11:07 - ',
 '4/29/24, 11:07 - ',
 '4/29/24, 11:08 - ',
 '4/30/24, 5:23 - ',
 '4/30/24, 5:23 - ',
 '4/30/24, 6:51 - ',
 '4/30/24, 6:55 - ',
 '4/30/24, 7:28 - ',
 '4/30/24, 7:28 - ',
 '5/1/24, 2:27 - ',
 '5/1/24, 2:27 - ',
 '5/1/24, 2:29 - ',
 '5/1/24, 6:33 - ',
 '5/1/24, 6:33 - ',
 '5/1/24, 6:33 - ',
 '5/4/24, 10:43 - ',
 '5/5/24, 2:46 - ',
 '5/5/24, 2:46 - ',
 '5/5/24, 2:46 - ',
 '5/5/24, 2:46 - ',
 '5/5/24, 2:46 - ',
 '5/5/24, 2:46 - ',
 '5/10/24, 11:42 - ',
 '5/10/24, 12:56 - ',
 '5/10/24, 12:59 - ',
 '5/12/24, 10:18 - ',
 '5/12/24, 10:18 - ',
 '5/12/24, 10:18 - ',
 '5/12/24, 10:18 - ',
 '5/12/24, 10:18 - ',
 '5/12/24, 10:18 - ',
 '5/12/24, 10:18 - ',
 '5/12/24, 10:18 - ',
 '5/12/24, 10:18 - ',
 '5/12/24, 10:18 - ',
 '5/12/24, 10:18 - ',
 '5/12/24, 10:18 - ',
 '5/12/24, 10:18 - ',
 '5/12/24, 10:18 - ',
 '5/12/24, 10:19 - ',
 '5/12/24, 10:19 - ',
 '5/12/24, 10:19 - ',
 '5/12/24, 10:19 - ',
 '5/12/24, 10:19 - ',
 '5/12/24, 10:19 - ',
 '5/12/24, 10:19 - ',
 '5/18/24, 11:39 - ',
 '5/18/24, 11:40 - ',
 '5/19/24, 1:25 - ',
 '5/19/24, 1:26 - ',
 '5/19/24, 1:26 - ',
 '5/19/24, 1:26 - ',
 '5/19/24, 1:26 - ',
 '5/19/24, 1:26 - ',
 '5/19/24, 1:26 - ',
 '5/19/24, 1:27 - ',
 '5/19/24, 1:27 - ',
 '5/19/24, 1:27 - ',
 '5/19/24, 1:27 - ',
 '6/4/24, 7:42 - ',
 '6/4/24, 7:42 - ',
 '8/25/24, 9:38 - ',
 '9/1/24, 2:34 - ',
 '9/1/24, 2:34 - ',
 '9/9/24, 10:53 - ',
 '9/9/24, 10:53 - ',
 '9/9/24, 10:55 - ',
 '9/9/24, 2:29 - ',
 '9/10/24, 2:21 - ',
 '9/10/24, 2:21 - ',
 '9/12/24, 9:37 - ',
 '9/12/24, 9:42 - ',
 '9/14/24, 6:26 - ',
 '9/14/24, 6:26 - ',
 '9/14/24, 6:30 - ',
 '9/14/24, 6:38 - ',
 '9/14/24, 7:13 - ',
 '9/14/24, 7:13 - ',
 '9/14/24, 7:44 - ',
 '9/27/24, 11:39 - ',
 '9/27/24, 2:14 - ',
 '9/27/24, 2:26 - ',
 '10/11/24, 10:12 - ',
 '10/11/24, 10:12 - ',
 '10/11/24, 10:12 - ',
 '10/11/24, 10:12 - ',
 '10/11/24, 10:22 - ',
 '10/11/24, 10:22 - ',
 '10/11/24, 11:35 - ',
 '10/12/24, 9:07 - ',
 '10/12/24, 9:07 - ',
 '10/12/24, 9:42 - ',
 '10/12/24, 9:42 - ',
 '10/12/24, 9:42 - ',
 '10/12/24, 9:44 - ',
 '11/7/24, 3:00 - ',
 '11/7/24, 3:00 - ',
 '11/7/24, 3:00 - ',
 '11/7/24, 3:02 - ',
 '11/7/24, 7:54 - ',
 '11/14/24, 9:05 - ',
 '11/16/24, 2:03 - ',
 '11/20/24, 1:09 - ',
 '11/20/24, 1:34 - ',
 '11/20/24, 1:43 - ',
 '11/20/24, 1:53 - ',
 '11/20/24, 1:54 - ',
 '11/20/24, 1:54 - ',
 '11/20/24, 7:55 - ',
 '11/20/24, 10:06 - ',
 '11/20/24, 10:06 - ',
 '11/20/24, 11:19 - ',
 '11/20/24, 11:19 - ',
 '11/20/24, 11:19 - ',
 '11/20/24, 11:19 - ',
 '11/20/24, 11:19 - ',
 '11/20/24, 11:19 - ',
 '11/20/24, 11:19 - ',
 '11/20/24, 11:19 - ',
 '11/20/24, 11:35 - ',
 '11/20/24, 11:36 - ',
 '11/20/24, 11:36 - ',
 '11/20/24, 11:36 - ',
 '11/20/24, 11:37 - ',
 '11/20/24, 11:37 - ',
 '11/20/24, 11:37 - ',
 '11/20/24, 11:37 - ',
 '11/21/24, 8:12 - ',
 '11/21/24, 8:12 - ',
 '11/21/24, 8:12 - ',
 '11/22/24, 8:28 - ',
 '11/25/24, 9:02 - ',
 '11/25/24, 9:02 - ',
 '12/6/24, 8:06 - ',
 '12/6/24, 8:06 - ',
 '12/6/24, 8:06 - ',
 '12/6/24, 8:07 - ',
 '12/11/24, 11:15 - ',
 '12/11/24, 11:16 - ',
 '12/11/24, 11:16 - ',
 '12/11/24, 11:16 - ',
 '12/11/24, 11:16 - ',
 '12/11/24, 11:16 - ',
 '12/11/24, 11:16 - ',
 '12/15/24, 8:17 - ',
 '12/15/24, 8:22 - ',
 '12/26/24, 9:43 - ',
 '12/26/24, 9:43 - ',
 '12/26/24, 9:44 - ',
 '12/26/24, 9:44 - ',
 '12/26/24, 9:44 - ',
 '12/31/24, 4:59 - ',
 '12/31/24, 5:04 - ',
 '12/31/24, 5:04 - ',
 '12/31/24, 5:05 - ',
 '12/31/24, 5:05 - ',
 '1/1/25, 10:17 - ',
 '1/1/25, 10:23 - ',
 '1/12/25, 11:21 - ',
 '1/12/25, 11:21 - ',
 '1/12/25, 11:47 - ',
 '1/12/25, 11:48 - ',
 '1/12/25, 11:50 - ',
 '1/12/25, 11:51 - ',
 '1/12/25, 11:51 - ',
 '1/12/25, 11:51 - ',
 '1/12/25, 11:52 - ',
 '1/12/25, 11:52 - ',
 '1/12/25, 11:52 - ',
 '1/12/25, 11:52 - ',
 '1/12/25, 11:52 - ',
 '1/12/25, 11:52 - ',
 '1/12/25, 11:53 - ',
 '1/12/25, 11:53 - ',
 '1/12/25, 11:53 - ',
 '1/12/25, 11:53 - ',
 '1/12/25, 11:53 - ',
 '1/12/25, 11:53 - ',
 '1/12/25, 11:54 - ',
 '1/12/25, 11:54 - ',
 '1/12/25, 11:54 - ',
 '1/12/25, 11:54 - ',
 '1/12/25, 11:54 - ',
 '1/12/25, 11:54 - ',
 '1/12/25, 11:54 - ',
 '1/12/25, 11:54 - ',
 '1/12/25, 11:54 - ',
 '2/17/25, 8:24 - ',
 '2/17/25, 9:41 - ',
 '2/18/25, 3:42 - ',
 '2/18/25, 3:43 - ',
 '2/18/25, 3:47 - ',
 '2/18/25, 3:53 - ',
 '2/18/25, 3:53 - ',
 '2/18/25, 3:54 - ',
 '2/18/25, 3:54 - ',
 '2/18/25, 3:54 - ',
 '2/18/25, 3:54 - ',
 '2/18/25, 3:55 - ',
 '2/22/25, 11:46 - ',
 '2/27/25, 3:44 - ',
 '3/1/25, 1:26 - ',
 '3/1/25, 2:35 - ',
 '3/1/25, 2:35 - ',
 '3/1/25, 2:38 - ',
 '3/1/25, 8:57 - ',
 '3/3/25, 11:01 - ',
 '3/3/25, 11:01 - ',
 '3/3/25, 11:35 - ',
 '3/3/25, 1:18 - ',
 '3/3/25, 2:42 - ',
 '3/3/25, 2:43 - ',
 '3/3/25, 4:15 - ',
 '3/3/25, 4:16 - ',
 '3/3/25, 4:17 - ',
 '3/3/25, 6:23 - ',
 '3/4/25, 11:11 - ',
 '3/4/25, 8:16 - ',
 '3/5/25, 12:12 - ',
 '3/5/25, 12:12 - ',
 '3/5/25, 12:12 - ',
 '3/5/25, 12:13 - ',
 '3/5/25, 12:13 - ',
 '3/5/25, 12:14 - ',
 '3/5/25, 12:15 - ',
 '3/5/25, 12:15 - ',
 '3/5/25, 12:15 - ',
 '3/5/25, 12:15 - ',
 '3/5/25, 12:15 - ',
 '3/5/25, 12:16 - ',
 '3/5/25, 12:16 - ',
 '3/5/25, 12:16 - ',
 '3/5/25, 12:16 - ',
 '3/5/25, 12:17 - ',
 '3/5/25, 12:17 - ',
 '3/5/25, 12:17 - ',
 '3/5/25, 12:17 - ',
 '3/5/25, 12:17 - ',
 '3/5/25, 12:17 - ',
 '3/5/25, 12:17 - ',
 '3/5/25, 12:17 - ',
 '3/5/25, 12:18 - ',
 '3/5/25, 12:18 - ',
 '3/5/25, 12:18 - ',
 '3/5/25, 12:21 - ',
 '3/5/25, 12:21 - ',
 '3/5/25, 12:21 - ',
 '3/5/25, 12:21 - ',
 '3/5/25, 12:22 - ',
 '3/5/25, 12:24 - ',
 '3/5/25, 12:25 - ',
 '3/5/25, 12:25 - ',
 '3/5/25, 12:25 - ',
 '3/5/25, 12:25 - ',
 '3/5/25, 12:26 - ',
 '3/5/25, 12:26 - ',
 '3/6/25, 10:19 - ',
 '3/27/25, 2:49 - ',
 '3/29/25, 9:33 - ',
 '3/30/25, 7:03 - ',
 '4/5/25, 12:28 - ',
 '4/5/25, 12:28 - ',
 '4/5/25, 2:09 - ',
 '4/5/25, 2:09 - ',
 '4/9/25, 11:36 - ',
 '4/10/25, 3:26 - ',
 '4/10/25, 3:26 - ',
 '4/10/25, 3:26 - ',
 '4/10/25, 3:30 - ',
 '4/10/25, 3:30 - ',
 '4/10/25, 3:30 - ',
 '4/10/25, 3:31 - ',
 '4/10/25, 3:31 - ',
 '4/10/25, 6:07 - ',
 '4/11/25, 11:02 - ',
 '4/20/25, 8:33 - ',
 '4/20/25, 8:51 - ',
 '4/20/25, 8:52 - ',
 '4/20/25, 8:52 - ',
 '4/20/25, 8:53 - ',
 '4/20/25, 8:53 - ',
 '4/20/25, 9:08 - ',
 '4/20/25, 9:06 - ',
 '4/24/25, 10:17 - ',
 '4/27/25, 12:04 - ',
 '4/27/25, 12:04 - ',
 '4/29/25, 6:37 - ',
 '4/29/25, 6:37 - ',
 '4/30/25, 11:20 - ',
 '4/30/25, 11:20 - ',
 '4/30/25, 11:20 - ',
 '4/30/25, 11:20 - ',
 '4/30/25, 11:24 - ',
 '5/1/25, 9:06 - ',
 '5/1/25, 9:07 - ',
 '5/1/25, 9:07 - ',
 '5/2/25, 8:14 - ',
 '5/2/25, 8:15 - ',
 '5/2/25, 8:17 - ',
 '5/2/25, 8:17 - ',
 '5/2/25, 8:31 - ',
 '5/2/25, 8:48 - ',
 '5/2/25, 8:50 - ',
 '5/2/25, 8:50 - ',
 '5/7/25, 4:16 - ',
 '5/9/25, 3:37 - ',
 '5/9/25, 4:19 - ',
 '5/9/25, 9:45 - ',
 '5/15/25, 12:20 - ']

In [11]:
df = pd.DataFrame({'user_message': messages, 'message_date': dates})
# convert message_date type
df['message_date'] = pd.to_datetime(df['message_date'], format='%m/%d/%y, %H:%M - ')

df.rename(columns={'message_date': 'date'}, inplace=True)

In [13]:
df.shape

(555, 2)

In [17]:
df.head()

,date,user,message
0,2023-09-07 09:21:00,group_notification,Messages and calls are end-to-end encrypted. O...
1,2023-10-10 12:32:00,group_notification,Akshat Jain TMU is a contact\n
2,2023-10-10 12:32:00,Akshat Jain TMU,Hi\n
3,2023-10-10 12:32:00,Akshat Jain TMU,<Media omitted>\n
4,2023-10-31 09:06:00,Akshat Jain TMU,Bhai m ne jo kal likhaya tha bo semd kro do\n

In [16]:
users = []
messages = []
for message in df['user_message']:
    entry = re.split(r'([\w\W]+?):\s', message)
    if entry[1:]:  # user name
        users.append(entry[1])
        messages.append(" ".join(entry[2:]))
    else:
        users.append('group_notification')
        messages.append(entry[0])

df['user'] = users
df['message'] = messages
df.drop(columns=['user_message'], inplace=True)

KeyError: 'user_message'

In [18]:
df.head()

,date,user,message
0,2023-09-07 09:21:00,group_notification,Messages and calls are end-to-end encrypted. O...
1,2023-10-10 12:32:00,group_notification,Akshat Jain TMU is a contact\n
2,2023-10-10 12:32:00,Akshat Jain TMU,Hi\n
3,2023-10-10 12:32:00,Akshat Jain TMU,<Media omitted>\n
4,2023-10-31 09:06:00,Akshat Jain TMU,Bhai m ne jo kal likhaya tha bo semd kro do\n

In [20]:
df['year']=df['date'].dt.year

In [21]:
df.head()

,date,user,message,year
0,2023-09-07 09:21:00,group_notification,Messages and calls are end-to-end encrypted. O...,2023
1,2023-10-10 12:32:00,group_notification,Akshat Jain TMU is a contact\n,2023
2,2023-10-10 12:32:00,Akshat Jain TMU,Hi\n,2023
3,2023-10-10 12:32:00,Akshat Jain TMU,<Media omitted>\n,2023
4,2023-10-31 09:06:00,Akshat Jain TMU,Bhai m ne jo kal likhaya tha bo semd kro do\n,2023

In [24]:
df['month']=df['date'].dt.month_name()

In [26]:
df['day']=df['date'].dt.day

In [27]:
df['hour']=df['date'].dt.hour

In [28]:
df['minute']=df['date'].dt.minute

In [29]:
df.head()

,date,user,message,year,month,day,hour,minute
0,2023-09-07 09:21:00,group_notification,Messages and calls are end-to-end encrypted. O...,2023,September,7,9,21
1,2023-10-10 12:32:00,group_notification,Akshat Jain TMU is a contact\n,2023,October,10,12,32
2,2023-10-10 12:32:00,Akshat Jain TMU,Hi\n,2023,October,10,12,32
3,2023-10-10 12:32:00,Akshat Jain TMU,<Media omitted>\n,2023,October,10,12,32
4,2023-10-31 09:06:00,Akshat Jain TMU,Bhai m ne jo kal likhaya tha bo semd kro do\n,2023,October,31,9,6